name: ci

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: user/app:test
  LATEST_TAG: user/app:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export to Docker
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            DOCKERFILE_PATH_1= NAaaS-M-Dops/NAaaS/Spark/Dockerfile
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
