name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you want to use

    - name: Determine changed Python files
      id: changed-files
      run: |
        LATEST_COMMIT=$(git log -1 --format='%H')
        PREVIOUS_COMMIT=$(git log -2 --skip=1 --format='%H')
        CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT $LATEST_COMMIT --diff-filter=d -- "**/*.py")
        echo "::set-output name=changed_files::${CHANGED_FILES}"

    - name: Get all changed .py   
      id: changed-files-excluded
      uses: tj-actions/changed-files@v36
      with:
          files: |
            NAaaS-M-Dops/NAaaS/Topic\ Extraction_mlflow_test
            **.py
            
    - name: Install dependencies
      if: steps.changed-files-excluded.outputs.any_changed == 'true'
      run: pip install -r NAaaS/Topic\ Extraction_mlflow_test/requirements.txt
    
            
    - name: Run Mlflow
      if: steps.changed-files-excluded.outputs.any_changed == 'true'
      run: |
          echo ::set-output name=version::$(cat NAaaS/Topic\ Extraction_mlflow_test/test.txt)
          echo ${{ steps.vars.outputs.version }}
          echo "Init_accuracy=$(cat NAaaS/Topic\ Extraction_mlflow_test/test.txt)" >> $GITHUB_OUTPUT
          run: python -m NAaaS/Topic\ Extraction_mlflow_test/Test.py
          echo "Final_accuracy=$(cat NAaaS/Topic\ Extraction_mlflow_test/test.txt)" >> $GITHUB_OUTPUT
   
              
            
#     - name: Compare accuracies and echo message
#       if: steps.changed-files-excluded.outputs.any_changed == 'true'
#       run: |
#           initial_accuracy=$(grep -oP 'initial_accuracy=\K[^ ]+' $GITHUB_OUTPUT)
#           final_accuracy=$(grep -oP 'final_accuracy=\K[^ ]+' $GITHUB_OUTPUT)
#           initial_accuracy_float=$(echo "$initial_accuracy" | awk '{printf "%.2f", $0}')
#           final_accuracy_float=$(echo "$final_accuracy" | awk '{printf "%.2f", $0}'
#            if (( $(echo "$final_accuracy_float > $initial_accuracy_float" | bc -l) )); then
#             echo "Accuracy increased from $initial_accuracy to $final_accuracy"
#           elif (( $(echo "$final_accuracy_float < $initial_accuracy_float" | bc -l) )); then
#             echo "Accuracy decreased from $initial_accuracy to $final_accuracy"
#           else
#             echo "Accuracy remained the same at $initial_accuracy"
#           fi
          
#     - name: Run tests and coverage
#       run: |
#         python -m pytest --cov= ${{ steps.changed-files-excluded.outputs.all_changed_files }}
#         coverage xml -o coverage.xml

#     - name: Upload coverage report
#       uses: codecov/codecov-action@v2
#       with:
#         file: coverage.xml
#         fail_ci_if_error: true
