name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you want to use

    - name: Determine changed Python files
      id: changed-files
      run: |
        LATEST_COMMIT=$(git log -1 --format='%H')
        PREVIOUS_COMMIT=$(git log -2 --skip=1 --format='%H')
        CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT $LATEST_COMMIT --diff-filter=d -- "**/*.py")
        echo "::set-output name=changed_files::${CHANGED_FILES}"

    - name: Get all changed .py   
      id: changed-files-excluded
      uses: tj-actions/changed-files@v36
      with:
          files: |
            NAaaS-M-Dops/NAaaS/Topic\ Extraction_mlflow_test
            **.py
            
    - name: Install dependencies
      if: steps.changed-files-excluded.outputs.any_changed == 'true'
      run: pip install -r NAaaS/Topic\ Extraction_mlflow_test/requirements.txt
    
            
    - name: Run Mlflow
      if: steps.changed-files-excluded.outputs.any_changed == 'true'
      run: python -m NAaaS/Topic\ Extraction_mlflow_test/Test
        
          
                            
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run tests and coverage
      run: echo "Starting"
    
    - name: Install dependencies
      run: |
        make install
        with:
          files: NAaaS-M-Dops/NAaaS/Topic\ Extraction_mlflow_test
    
    - name: Lint
      run: |
        make lint
        with:
          files: NAaaS-M-Dops/NAaaS/Topic\ Extraction_mlflow_test
    
    - name: Test
      run: |
        make test
        with:
          files: |
            NAaaS-M-Dops/NAaaS/Topic\ Extraction_mlflow_test

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        file: |
          coverage.xml
        fail_ci_if_error: true
